/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Payroll_IFrame;

import static MAIN_FRAME.mainFrame.pname;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author TRAINEE
 */
public class genIFrame extends javax.swing.JInternalFrame {

    
    ResultSet rs=null;
    PreparedStatement pst=null;
    Connection conn=null;
    Statement stmt=null;
     
    final void updateT(){
        
        try{
            String query="select employeeid,surname,firstname,STARTDATE,ENDDATE,PAYMENTDATE from empdata3 where paymentdate='"+((JTextField)PD.getDateEditor().getUiComponent()).getText()+"'";
            
            pst=conn.prepareStatement(query);

            rs=pst.executeQuery();
            salTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void searchTableClick(){
        
        try{
           
            int row=salTable.getSelectedRow();
            String table_click=(salTable.getModel().getValueAt(row, 0).toString());
            

           String query="select employeeid,surname,firstname,designation,department,pagibig,philhealth,sss,food,transpo,Basicsalary,OVERTIME,NIGHTDIFF,HOLIDAYPAY,BONUS,LATES,UNDERTIME,ABSENCES,LOAN,ti,tp,GROSSPAY,NETPAY from empdata3 where employeeid='"+table_click+"'";
            pst=conn.prepareStatement(query);
            rs=pst.executeQuery();

            if(rs.next()){
                empIDout.setText(rs.getString(1));
                surnameOut.setText(rs.getString(2));
                fnameOut.setText(rs.getString(3));
                designationOut.setText(rs.getString(4));
                deptOut.setText(rs.getString(5));
                pagibigOut.setText(rs.getString(6));
                philhealthOut.setText(rs.getString(7));
                sssOut.setText(rs.getString(8));
                foodOut.setText(rs.getString(9));
                transpoOut.setText(rs.getString(10));
                bpOut.setText(rs.getString(11));
                otOut.setText(rs.getString(12));
                ndOut.setText(rs.getString(13));
                hdOut.setText(rs.getString(14));
                bonusOut.setText(rs.getString(15));
                latesOut.setText(rs.getString(16));
                udOut.setText(rs.getString(17));
                absencesOut.setText(rs.getString(18));
                loanOut.setText(rs.getString(19));
                tiOut.setText(rs.getString(20));
                tpOut.setText(rs.getString(21));
                grossOut.setText(rs.getString(22));
                
            }
            updateT();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
    public void openConnection(){
        try {
            Class.forName("org.h2.Driver");
            conn = DriverManager.getConnection("jdbc:h2:~/Peeroll;IGNORECASE=TRUE","edmon", "" );
        }
         catch( Exception e )
        {
            JOptionPane.showMessageDialog(null, "PROGRAM ALREADY IN USE.");
        }
    }
    
    public genIFrame() {
        initComponents();
         openConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ED = new com.toedter.calendar.JDateChooser();
        jLabel64 = new javax.swing.JLabel();
        SD = new com.toedter.calendar.JDateChooser();
        jPanel9 = new javax.swing.JPanel();
        PD = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        salTable = new javax.swing.JTable(){
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                // This is how we disable editing:
                return false;
            }
        };
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        surnameOut = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        designationOut = new javax.swing.JLabel();
        empIDout = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        deptOut = new javax.swing.JLabel();
        fnameOut = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ed = new javax.swing.JLabel();
        sd = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        pd = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel104 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        bonusOut = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        transpoOut = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        absencesOut = new javax.swing.JLabel();
        bpOut = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        hdOut = new javax.swing.JLabel();
        pagibigOut = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        philhealthOut = new javax.swing.JLabel();
        otOut = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        udOut = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        loanOut = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        foodOut = new javax.swing.JLabel();
        ndOut = new javax.swing.JLabel();
        sssOut = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        month13Out = new javax.swing.JLabel();
        latesOut = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        grossOut = new javax.swing.JLabel();
        tiOut = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        netOut = new javax.swing.JLabel();
        tpOut = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        caOut = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1012, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Payment Period", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 51, 0))); // NOI18N

        ED.setDateFormatString("yyyy-MM-dd");

        jLabel64.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel64.setText("TO");

        SD.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SD, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel64)
                .addGap(12, 12, 12)
                .addComponent(ED, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel64)
                    .addComponent(ED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Payment Date", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 51, 0))); // NOI18N

        PD.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PD, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        salTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Employee Name", "Start Date", "End Date", "Payment Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        salTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        salTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(salTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 470, 233));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true), "PAYSLIP SUMMARY", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Berlin Sans FB", 0, 18), new java.awt.Color(51, 51, 51))); // NOI18N

        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel77.setText("Full Name:");

        surnameOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel79.setText("Employee ID:");

        jLabel80.setText("Designation:");

        designationOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        empIDout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel83.setText("Department:");

        deptOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fnameOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Payment Period", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 51))); // NOI18N

        jLabel7.setText("TO");

        ed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        sd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sd, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ed, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sd, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ed, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Payment Date", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        pd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pd, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pd, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true), "Payslip Summary", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 51, 51))); // NOI18N

        jLabel104.setText("Absences:");

        jLabel91.setText("PAG-BIG:");

        bonusOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel103.setText("Undertime:");

        transpoOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel92.setText("SSS:");

        absencesOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bpOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel98.setText("Bonus:");

        hdOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pagibigOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel108.setText("Loan Deductions:");

        philhealthOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        otOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel90.setText("PHILHEALTH:");

        udOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel97.setText("Holiday Pay:");

        jLabel102.setText("Lates:");

        loanOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel36.setText("Basic Pay:");

        foodOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ndOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        sssOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel86.setText("Night Diffs:");

        jLabel85.setText("Overtime Pay:");

        month13Out.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        latesOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel112.setText("TaxableIncome:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Gross Pay:");

        grossOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tiOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setText("Net Pay:");

        jLabel111.setText("Tax Payable:");

        netOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tpOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel101.setText("Food:");

        jLabel126.setText("Transpo:");

        caOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel127.setText("Cash Adv.:");

        jLabel109.setText("13th Month Pay:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel85, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel97)
                                    .addComponent(jLabel98)))
                            .addComponent(jLabel86, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jLabel13)
                    .addComponent(jLabel112)
                    .addComponent(jLabel101)
                    .addComponent(jLabel126)
                    .addComponent(jLabel127))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bpOut, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(otOut, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ndOut, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hdOut, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bonusOut, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(foodOut, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transpoOut, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel91)
                                    .addComponent(jLabel102)
                                    .addComponent(jLabel92)
                                    .addComponent(jLabel103))
                                .addGap(2, 2, 2))
                            .addComponent(jLabel108, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel90, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel104, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tiOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(grossOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel111, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(caOut, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel109)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pagibigOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(philhealthOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sssOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(latesOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(udOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(absencesOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loanOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(month13Out, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(tpOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(netOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel90, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(philhealthOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel36))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pagibigOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel91, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel85, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(6, 6, 6)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(sssOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel92)))
                                .addComponent(jLabel86, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(6, 6, 6)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(latesOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel102, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(jLabel97, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(udOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel103)))
                                .addComponent(jLabel98, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(absencesOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel101)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel126))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(bpOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(otOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ndOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(hdOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bonusOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(foodOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(transpoOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel104)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loanOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel108, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(month13Out, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(caOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel127)
                    .addComponent(jLabel109))
                .addGap(26, 26, 26)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tpOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tiOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(grossOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(netOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel112)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel111)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel33)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel83)
                                .addGap(4, 4, 4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel80, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel77, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel79, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empIDout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(surnameOut, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fnameOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(deptOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(designationOut, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(empIDout, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(surnameOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fnameOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(deptOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(designationOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 315, Short.MAX_VALUE)
                .addGap(329, 329, 329))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 480, 545));

        jButton1.setText("PRINT PAYSLIP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 168, 42));

        jButton2.setText("FIND");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 90, -1));

        jButton5.setText("DELETE RECORD");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 140, 40));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESOURCES/pritn.png"))); // NOI18N
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 40, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESOURCES/Delete_2.png"))); // NOI18N
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("PRINT PAYSLIP");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(339, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salTableMouseClicked
       try{
            int row=salTable.getSelectedRow();
            String table_click=(salTable.getModel().getValueAt(row, 0).toString());

            String query="select employeeid,surname,firstname,designation,department,pagibig,philhealth,sss,food,transpo,Basicsalary,OVERTIME,NIGHTDIFF,HOLIDAYPAY,BONUS,LATES,UNDERTIME,ABSENCES,LOAN,ti,tp,GROSSPAY,NETPAY,STARTDATE,ENDDATE,PAYMENTDATE,CA,MONTH13 from empdata3 where employeeid='"+table_click+"' AND paymentdate='"+((JTextField)PD.getDateEditor().getUiComponent()).getText()+"'";
            pst=conn.prepareStatement(query);
            rs=pst.executeQuery();

            if(rs.next()){
                empIDout.setText(rs.getString(1));
                surnameOut.setText(rs.getString(2));
                fnameOut.setText(rs.getString(3));
                designationOut.setText(rs.getString(4));
                deptOut.setText(rs.getString(5));
                pagibigOut.setText(rs.getString(6));
                philhealthOut.setText(rs.getString(7));
                sssOut.setText(rs.getString(8));
                foodOut.setText(rs.getString(9));
                transpoOut.setText(rs.getString(10));
                bpOut.setText(rs.getString(11));
                otOut.setText(rs.getString(12));
                ndOut.setText(rs.getString(13));
                hdOut.setText(rs.getString(14));
                bonusOut.setText(rs.getString(15));
                latesOut.setText(rs.getString(16));
                udOut.setText(rs.getString(17));
                absencesOut.setText(rs.getString(18));
                loanOut.setText(rs.getString(19));
                tiOut.setText(rs.getString(20));
                tpOut.setText(rs.getString(21));
                grossOut.setText(rs.getString(22));
                netOut.setText(rs.getString(23));
                sd.setText(rs.getDate(24).toString());
                ed.setText(rs.getDate(25).toString());
                pd.setText(rs.getDate(26).toString());
                caOut.setText(rs.getString(27));
                month13Out.setText(rs.getString(28));
 
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    
    }//GEN-LAST:event_salTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        double sss=0;
        double phil=0;
        double pagibig=0;
        double total=0;
        
        String what=sssOut.getText();
        
        if(what.equals("")){
            total=0;
        }
        else{
            sss=Double.parseDouble(sssOut.getText());
            phil=Double.parseDouble(philhealthOut.getText());
            pagibig=Double.parseDouble(pagibigOut.getText());
            total=0;
            total=sss+phil+pagibig;
        }
        int p=JOptionPane.showConfirmDialog(null, "GENERATE PAYSLIP?","PAYSLIP",JOptionPane.YES_NO_OPTION);
        
        if (p==0) {
            
        
        try {
        Document document=new Document();
        PdfWriter.getInstance(document, new FileOutputStream("Payslip.pdf"));
        document.setPageSize(PageSize.A4);
        document.open();
        
         
        PdfPTable table1=new PdfPTable(2);
        table1.setWidthPercentage(107);
        table1.setSpacingBefore(1);
        table1.getDefaultCell().setBorder(PdfPCell.NO_BORDER);
        com.itextpdf.text.Font lfont;
            
        lfont=FontFactory.getFont(FontFactory.COURIER,9 ,Font.PLAIN,BaseColor.BLACK);
            
            PdfPCell t1=new PdfPCell(new Paragraph("Company: NISSI MEDICAL CLINIC",lfont));
            PdfPCell t2=new PdfPCell(new Paragraph("Pay Period Start: "+sd.getText()+"",lfont));
            
            PdfPCell l1=new PdfPCell(new Paragraph("Employee ID: "+empIDout.getText()+"",lfont));
            PdfPCell l2=new PdfPCell(new Paragraph("Pay Period End: "+ed.getText()+"",lfont));
            
            PdfPCell l3=new PdfPCell(new Paragraph("Employee Name: "+fnameOut.getText()+" "+surnameOut.getText()+"",lfont));
            PdfPCell l4=new PdfPCell(new Paragraph("Payment Date: "+pd.getText()+"",lfont));
            
            PdfPCell l5=new PdfPCell(new Paragraph("Postion: "+designationOut.getText()+"",lfont));
            PdfPCell l6=new PdfPCell(new Paragraph(""));
        
            
            t1.setHorizontalAlignment(Element.ALIGN_LEFT);
            t2.setHorizontalAlignment(Element.ALIGN_RIGHT);
            l1.setHorizontalAlignment(Element.ALIGN_LEFT);
            l2.setHorizontalAlignment(Element.ALIGN_RIGHT);
            l3.setHorizontalAlignment(Element.ALIGN_LEFT);
            l4.setHorizontalAlignment(Element.ALIGN_RIGHT);
            l5.setHorizontalAlignment(Element.ALIGN_LEFT);
            l6.setHorizontalAlignment(Element.ALIGN_RIGHT);
            
            t1.setBorder(Rectangle.NO_BORDER);
            t2.setBorder(Rectangle.NO_BORDER);
            l1.setBorder(Rectangle.NO_BORDER);
            l2.setBorder(Rectangle.NO_BORDER);
            l3.setBorder(Rectangle.NO_BORDER);
            l4.setBorder(Rectangle.NO_BORDER);
            l5.setBorder(Rectangle.NO_BORDER);
            l6.setBorder(Rectangle.NO_BORDER);
            
            table1.addCell(t1);
            table1.addCell(t2);
            table1.addCell(l1);
            table1.addCell(l2);
            table1.addCell(l3);
            table1.addCell(l4);
            table1.addCell(l5);
            table1.addCell(l6);
            
            
        document.add(table1);
        //END OF 1ST TABLE
        
        
        
        PdfPTable table=new PdfPTable(7);
            table.getDefaultCell().setBorder(PdfPCell.NO_BORDER);
            table.setWidthPercentage(107);
            table.setWidths(new int[]{170,100,170,95,160,100,190});
            table.setSpacingAfter(15);
            table.setSpacingBefore(8);
            com.itextpdf.text.Font tfont;
            com.itextpdf.text.Font tfont1;
            com.itextpdf.text.Font tfont2;
            com.itextpdf.text.Font small;
            
            small=FontFactory.getFont(FontFactory.COURIER,6 ,Font.PLAIN,BaseColor.BLACK);
            tfont=FontFactory.getFont(FontFactory.COURIER,9 ,Font.PLAIN,BaseColor.BLACK);
            tfont1=FontFactory.getFont(FontFactory.COURIER_BOLD,11 ,Font.PLAIN,BaseColor.BLACK);
            tfont2=FontFactory.getFont(FontFactory.COURIER_BOLD,10 ,Font.PLAIN,BaseColor.BLACK);
            
            PdfPCell cell=new PdfPCell(new Paragraph("PAYSLIP",FontFactory.getFont(FontFactory.COURIER_BOLD,15 ,Font.PLAIN,BaseColor.WHITE)));
            cell.setColspan(7);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setBackgroundColor(BaseColor.DARK_GRAY);
            table.addCell(cell);
 
            PdfPCell cell1=new PdfPCell(new Paragraph("BASIC PAY:",tfont));
            PdfPCell cell2=new PdfPCell(new Paragraph(bpOut.getText()+".00",tfont));
            PdfPCell cell3=new PdfPCell(new Paragraph("",tfont));
            PdfPCell cell4=new PdfPCell(new Paragraph(""));
            PdfPCell cell5=new PdfPCell(new Paragraph(""));
            PdfPCell cell6=new PdfPCell(new Paragraph(""));
            PdfPCell cell7=new PdfPCell(new Paragraph(""));
            
            PdfPCell cell8=new PdfPCell(new Paragraph("Overtime Pay:",tfont));
            PdfPCell cell9=new PdfPCell(new Paragraph(otOut.getText(),tfont));
            PdfPCell cell10=new PdfPCell(new Paragraph("Lates:",tfont));
            PdfPCell cell11=new PdfPCell(new Paragraph(latesOut.getText(),tfont));
            PdfPCell cell12=new PdfPCell(new Paragraph("Gross Pay:",tfont));
            PdfPCell cell13=new PdfPCell(new Paragraph(grossOut.getText(),tfont));
            PdfPCell cell14=new PdfPCell(new Paragraph("Received a sum of:",tfont));
            
            PdfPCell cell15=new PdfPCell(new Paragraph("Night Diff.:",tfont));
            PdfPCell cell16=new PdfPCell(new Paragraph(ndOut.getText(),tfont));
            PdfPCell cell17=new PdfPCell(new Paragraph("Absences:",tfont));
            PdfPCell cell18=new PdfPCell(new Paragraph(absencesOut.getText(),tfont));
            PdfPCell cell19=new PdfPCell(new Paragraph("Tax Payable:",tfont));
            PdfPCell cell20=new PdfPCell(new Paragraph(tpOut.getText(),tfont));
            PdfPCell cell21=new PdfPCell(new Paragraph("P "+netOut.getText(),tfont2));
            
            PdfPCell cell22=new PdfPCell(new Paragraph("Holiday Pay:",tfont));
            PdfPCell cell23=new PdfPCell(new Paragraph(hdOut.getText(),tfont));
            PdfPCell cell24=new PdfPCell(new Paragraph("Undertime:",tfont));
            PdfPCell cell25=new PdfPCell(new Paragraph(udOut.getText(),tfont));
            PdfPCell cell26=new PdfPCell(new Paragraph("Statutory Deduct.:",tfont));
            PdfPCell cell27=new PdfPCell(new Paragraph(Double.toString(total),tfont));
            PdfPCell cell28=new PdfPCell(new Paragraph(""));
            
            PdfPCell cell29=new PdfPCell(new Paragraph("Food Allowance:",tfont));
            PdfPCell cell30=new PdfPCell(new Paragraph(foodOut.getText(),tfont));
            PdfPCell cell31=new PdfPCell(new Paragraph("SSS:",tfont));
            PdfPCell cell32=new PdfPCell(new Paragraph(sssOut.getText(),tfont));
            PdfPCell cell33=new PdfPCell(new Paragraph("(SSS,PHILHEALTH,PAGIBIG)",small));
            PdfPCell cell34=new PdfPCell(new Paragraph(""));
            PdfPCell cell35=new PdfPCell(new Paragraph(""));
            
            PdfPCell cell36=new PdfPCell(new Paragraph("Transpo Allowance:",tfont));
            PdfPCell cell37=new PdfPCell(new Paragraph(transpoOut.getText(),tfont));
            PdfPCell cell38=new PdfPCell(new Paragraph("PAG-IBIG:",tfont));
            PdfPCell cell39=new PdfPCell(new Paragraph(pagibigOut.getText(),tfont));
            PdfPCell cell40=new PdfPCell(new Paragraph("Cash Advance:",tfont));
            PdfPCell cell41=new PdfPCell(new Paragraph(caOut.getText(),tfont));
            PdfPCell cell42=new PdfPCell(new Paragraph(""));
            
            PdfPCell cell43=new PdfPCell(new Paragraph("Bonuses:",tfont));
            PdfPCell cell44=new PdfPCell(new Paragraph(bonusOut.getText(),tfont));
            PdfPCell cell45=new PdfPCell(new Paragraph("PHILHEALTH:",tfont));
            PdfPCell cell46=new PdfPCell(new Paragraph(philhealthOut.getText(),tfont));
            PdfPCell cell47=new PdfPCell(new Paragraph(""));
            PdfPCell cell48=new PdfPCell(new Paragraph(""));
            PdfPCell cell49=new PdfPCell(new Paragraph("__________________",tfont));
            
            PdfPCell cell50=new PdfPCell(new Paragraph("13th Month Pay:",tfont));
            PdfPCell cell51=new PdfPCell(new Paragraph(month13Out.getText(),tfont));
            PdfPCell cell52=new PdfPCell(new Paragraph("Loan Deductions:",tfont));
            PdfPCell cell53=new PdfPCell(new Paragraph(loanOut.getText(),tfont));
            PdfPCell cell54=new PdfPCell(new Paragraph(""));
            PdfPCell cell55=new PdfPCell(new Paragraph(""));
            PdfPCell cell56=new PdfPCell(new Paragraph("Signature",tfont));
            
            PdfPCell cell57=new PdfPCell(new Paragraph("",tfont));
            PdfPCell cell58=new PdfPCell(new Paragraph("",tfont));
            PdfPCell cell59=new PdfPCell(new Paragraph("Taxable Income:                            .",tfont));
            PdfPCell cell60=new PdfPCell(new Paragraph(tiOut.getText(),tfont));
            PdfPCell cell61=new PdfPCell(new Paragraph(""));
            PdfPCell cell62=new PdfPCell(new Paragraph(""));
            PdfPCell cell63=new PdfPCell(new Paragraph(""));
            
     
            PdfPCell cell64=new PdfPCell(new Paragraph("GROSS PAY:",tfont1));
            PdfPCell cell65=new PdfPCell(new Paragraph(grossOut.getText(),tfont2));
            PdfPCell cell66=new PdfPCell(new Paragraph("TAX PAYABLES:",tfont1));
            PdfPCell cell67=new PdfPCell(new Paragraph(""));
            PdfPCell cell68=new PdfPCell(new Paragraph("NET PAY:",tfont1));
            PdfPCell cell69=new PdfPCell(new Paragraph(netOut.getText(),tfont2));
            PdfPCell cell70=new PdfPCell(new Paragraph(""));
            
                     
            cell1.setBorder(Rectangle.LEFT);
            cell2.setBorder(Rectangle.RIGHT);
            cell2.setHorizontalAlignment(Element.ALIGN_RIGHT);
            
            cell3.setBorder(Rectangle.NO_BORDER);
            cell4.setBorder(Rectangle.RIGHT);
            cell4.setHorizontalAlignment(Element.ALIGN_RIGHT);
            
            cell5.setBorder(Rectangle.NO_BORDER);
            cell6.setBorder(Rectangle.RIGHT);
            cell6.setHorizontalAlignment(Element.ALIGN_RIGHT);   
            cell7.setBorder(Rectangle.RIGHT);
            cell7.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            cell8.setBorder(Rectangle.LEFT);
            cell9.setBorder(Rectangle.RIGHT);
            cell9.setHorizontalAlignment(Element.ALIGN_RIGHT);
            
            cell10.setBorder(Rectangle.NO_BORDER);
            cell11.setBorder(Rectangle.RIGHT);
            cell11.setHorizontalAlignment(Element.ALIGN_RIGHT);
            
            cell12.setBorder(Rectangle.NO_BORDER);
            cell13.setBorder(Rectangle.RIGHT);
            cell13.setHorizontalAlignment(Element.ALIGN_RIGHT);   
            cell14.setBorder(Rectangle.RIGHT);
            cell14.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            cell15.setBorder(Rectangle.LEFT);
            cell16.setBorder(Rectangle.RIGHT);
            cell16.setHorizontalAlignment(Element.ALIGN_RIGHT);
            
            cell17.setBorder(Rectangle.NO_BORDER);
            cell18.setBorder(Rectangle.RIGHT);
            cell18.setHorizontalAlignment(Element.ALIGN_RIGHT);
            
            cell19.setBorder(Rectangle.NO_BORDER);
            cell20.setBorder(Rectangle.RIGHT);
            cell20.setHorizontalAlignment(Element.ALIGN_RIGHT);   
            cell21.setBorder(Rectangle.RIGHT);
            cell21.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            cell22.setBorder(Rectangle.LEFT);
            cell23.setBorder(Rectangle.RIGHT);
            cell23.setHorizontalAlignment(Element.ALIGN_RIGHT);
            
            cell24.setBorder(Rectangle.NO_BORDER);
            cell25.setBorder(Rectangle.RIGHT);
            cell25.setHorizontalAlignment(Element.ALIGN_RIGHT);
            
            cell26.setBorder(Rectangle.NO_BORDER);
            cell27.setBorder(Rectangle.RIGHT);
            cell27.setHorizontalAlignment(Element.ALIGN_RIGHT);   
            cell28.setBorder(Rectangle.RIGHT);
            cell28.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            cell29.setBorder(Rectangle.LEFT);
            cell30.setBorder(Rectangle.RIGHT);
            cell30.setHorizontalAlignment(Element.ALIGN_RIGHT);
            
            cell31.setBorder(Rectangle.NO_BORDER);
            cell32.setBorder(Rectangle.RIGHT);
            cell32.setHorizontalAlignment(Element.ALIGN_RIGHT);
            
            cell33.setBorder(Rectangle.NO_BORDER);
            cell34.setBorder(Rectangle.RIGHT);
            cell34.setHorizontalAlignment(Element.ALIGN_RIGHT);   
            cell35.setBorder(Rectangle.RIGHT);
            cell35.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            cell36.setBorder(Rectangle.LEFT);
            cell37.setBorder(Rectangle.RIGHT);
            cell37.setHorizontalAlignment(Element.ALIGN_RIGHT);
            
            cell38.setBorder(Rectangle.NO_BORDER);
            cell39.setBorder(Rectangle.RIGHT);
            cell39.setHorizontalAlignment(Element.ALIGN_RIGHT);
            
            cell40.setBorder(Rectangle.NO_BORDER);
            cell41.setBorder(Rectangle.RIGHT);
            cell41.setHorizontalAlignment(Element.ALIGN_RIGHT);   
            cell42.setBorder(Rectangle.RIGHT);
            cell42.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            cell43.setBorder(Rectangle.LEFT);
            cell44.setBorder(Rectangle.RIGHT);
            cell44.setHorizontalAlignment(Element.ALIGN_RIGHT);
            
            cell45.setBorder(Rectangle.NO_BORDER);
            cell46.setBorder(Rectangle.RIGHT);
            cell46.setHorizontalAlignment(Element.ALIGN_RIGHT);
            
            cell47.setBorder(Rectangle.NO_BORDER);
            cell48.setBorder(Rectangle.RIGHT);
            cell48.setHorizontalAlignment(Element.ALIGN_RIGHT);   
            cell49.setBorder(Rectangle.RIGHT);
            cell49.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            cell50.setBorder(Rectangle.LEFT);
            cell51.setBorder(Rectangle.RIGHT);
            cell51.setHorizontalAlignment(Element.ALIGN_RIGHT);
            
            cell52.setBorder(Rectangle.NO_BORDER);
            cell53.setBorder(Rectangle.RIGHT);
            cell53.setHorizontalAlignment(Element.ALIGN_RIGHT);
            
            cell54.setBorder(Rectangle.NO_BORDER);
            cell55.setBorder(Rectangle.RIGHT);
            cell55.setHorizontalAlignment(Element.ALIGN_RIGHT);   
            cell56.setBorder(Rectangle.RIGHT);
            cell56.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            cell57.setBorder(Rectangle.LEFT);
            cell58.setBorder(Rectangle.RIGHT);
            cell58.setHorizontalAlignment(Element.ALIGN_RIGHT);
            
            cell59.setBorder(Rectangle.NO_BORDER);
            cell60.setBorder(Rectangle.RIGHT);
            cell60.setHorizontalAlignment(Element.ALIGN_RIGHT);
            
            cell61.setBorder(Rectangle.NO_BORDER);
            cell62.setBorder(Rectangle.RIGHT);
            cell62.setHorizontalAlignment(Element.ALIGN_RIGHT);   
            cell63.setBorder(Rectangle.RIGHT);
            cell63.setHorizontalAlignment(Element.ALIGN_CENTER);
            
         
            cell64.setBorder(Rectangle.LEFT | Rectangle.TOP | Rectangle.BOTTOM );
            cell65.setBorder(Rectangle.RIGHT | Rectangle.TOP | Rectangle.BOTTOM);
            cell65.setHorizontalAlignment(Element.ALIGN_RIGHT);
            
            cell66.setBorder(Rectangle.TOP | Rectangle.BOTTOM);
            cell67.setBorder(Rectangle.RIGHT | Rectangle.TOP | Rectangle.BOTTOM);
            cell67.setHorizontalAlignment(Element.ALIGN_RIGHT);
            
            cell68.setBorder(Rectangle.TOP | Rectangle.BOTTOM);
            cell69.setBorder(Rectangle.RIGHT | Rectangle.TOP | Rectangle.BOTTOM);
            cell69.setHorizontalAlignment(Element.ALIGN_RIGHT);   
            cell70.setBorder(Rectangle.RIGHT | Rectangle.TOP | Rectangle.BOTTOM);
            cell70.setHorizontalAlignment(Element.ALIGN_CENTER);

           
           
            
            table.addCell(cell1);
            table.addCell(cell2);
            table.addCell(cell3);
            table.addCell(cell4);
            table.addCell(cell5);
            table.addCell(cell6);
            table.addCell(cell7);
            
            table.addCell(cell8);
            table.addCell(cell9);
            table.addCell(cell10);
            table.addCell(cell11);
            table.addCell(cell12);
            table.addCell(cell13);
            table.addCell(cell14);
            
            table.addCell(cell15);
            table.addCell(cell16);
            table.addCell(cell17);
            table.addCell(cell18);
            table.addCell(cell19);
            table.addCell(cell20);
            table.addCell(cell21);
            
            table.addCell(cell22);
            table.addCell(cell23);
            table.addCell(cell24);
            table.addCell(cell25);
            table.addCell(cell26);
            table.addCell(cell27);
            table.addCell(cell28);
            
            table.addCell(cell29);
            table.addCell(cell30);
            table.addCell(cell31);
            table.addCell(cell32);
            table.addCell(cell33);
            table.addCell(cell34);
            table.addCell(cell35);
            
            table.addCell(cell36);
            table.addCell(cell37);
            table.addCell(cell38);
            table.addCell(cell39);
            table.addCell(cell40);
            table.addCell(cell41);
            table.addCell(cell42);
            
            table.addCell(cell43);
            table.addCell(cell44);
            table.addCell(cell45);
            table.addCell(cell46);
            table.addCell(cell47);
            table.addCell(cell48);
            table.addCell(cell49);
            
            table.addCell(cell50);
            table.addCell(cell51);
            table.addCell(cell52);
            table.addCell(cell53);
            table.addCell(cell54);
            table.addCell(cell55);
            table.addCell(cell56);
            
            table.addCell(cell57);
            table.addCell(cell58);
            table.addCell(cell59);
            table.addCell(cell60);
            table.addCell(cell61);
            table.addCell(cell62);
            table.addCell(cell63);
                     
            
            table.addCell(cell64);
            table.addCell(cell65);
            table.addCell(cell66);
            table.addCell(cell67);
            table.addCell(cell68);
            table.addCell(cell69);
            table.addCell(cell70);

            document.add(table);   
            
        PdfPTable signs=new PdfPTable(2);
        signs.setWidthPercentage(107);
        signs.setSpacingBefore(0);
        signs.getDefaultCell().setBorder(PdfPCell.NO_BORDER);
            
        
            PdfPCell s1=new PdfPCell(new Paragraph("Manager's Signature:____________________",lfont));
            PdfPCell s2=new PdfPCell(new Paragraph("Prepared By: "+pname.getText()+"",lfont));

            
            s1.setHorizontalAlignment(Element.ALIGN_LEFT);
            s2.setHorizontalAlignment(Element.ALIGN_RIGHT);
            
            s1.setBorder(Rectangle.NO_BORDER);
            s2.setBorder(Rectangle.NO_BORDER);

            signs.addCell(s1);
            signs.addCell(s2);
            
            document.add(signs);
                
           /* com.itextpdf.text.List list=new com.itextpdf.text.List(true,20); //20 is max number of list
            list.add("EMPLOYEE ID");
            list.add("Bonuses");
            list.add("OVER TIME PAY");
            list.add("NIGHT DIFFERENTIAL");
            
            document.add(list);*/
           // 

        document.close();
         try{
             Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"C:\\Program Files\\EZPayroll\\Payslip.pdf");
             
         }
         catch (Exception ex){
             JOptionPane.showMessageDialog(null,ex);
         }
        
        
         }        
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        } 
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      try{
          String query="select employeeid,surname,firstname,startdate,enddate,paymentdate FROM EMPDATA3 where startdate='"+((JTextField)SD.getDateEditor().getUiComponent()).getText()+"' AND enddate='"+((JTextField)ED.getDateEditor().getUiComponent()).getText()+"' AND paymentdate='"+((JTextField)PD.getDateEditor().getUiComponent()).getText()+"' ORDER BY EMPLOYEEID";
          
          pst=conn.prepareStatement(query);
         
          rs=pst.executeQuery();
          
          salTable.setModel(DbUtils.resultSetToTableModel(rs));
          
          
      }
      
      
      catch(SQLException e){
          JOptionPane.showMessageDialog(null, e);
         
      }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      int p=JOptionPane.showConfirmDialog(null, "DELETE THIS RECORD?" , "DELETE EMPLOYEE DATA",JOptionPane.YES_NO_OPTION);
        if(p==0){
            try{
                String query="delete from EMPDATA3 where employeeid=? AND paymentdate=? AND enddate=? and startdate=?";
                pst=conn.prepareStatement(query);

                pst.setString(1,empIDout.getText());
                pst.setString(2,((JTextField)PD.getDateEditor().getUiComponent()).getText());
                pst.setString(3,((JTextField)ED.getDateEditor().getUiComponent()).getText());
                pst.setString(4,((JTextField)SD.getDateEditor().getUiComponent()).getText());
                
                
                
                pst.execute();
                JOptionPane.showMessageDialog(null,"Employee RECORD Deleted");
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
        updateT();
    }//GEN-LAST:event_jButton5ActionPerformed
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser ED;
    private com.toedter.calendar.JDateChooser PD;
    private com.toedter.calendar.JDateChooser SD;
    private javax.swing.JLabel absencesOut;
    private javax.swing.JLabel bonusOut;
    private javax.swing.JLabel bpOut;
    private javax.swing.JLabel caOut;
    private javax.swing.JLabel deptOut;
    private javax.swing.JLabel designationOut;
    private javax.swing.JLabel ed;
    private javax.swing.JLabel empIDout;
    private javax.swing.JLabel fnameOut;
    private javax.swing.JLabel foodOut;
    private javax.swing.JLabel grossOut;
    private javax.swing.JLabel hdOut;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel latesOut;
    private javax.swing.JLabel loanOut;
    private javax.swing.JLabel month13Out;
    private javax.swing.JLabel ndOut;
    private javax.swing.JLabel netOut;
    private javax.swing.JLabel otOut;
    private javax.swing.JLabel pagibigOut;
    private javax.swing.JLabel pd;
    private javax.swing.JLabel philhealthOut;
    private javax.swing.JTable salTable;
    private javax.swing.JLabel sd;
    private javax.swing.JLabel sssOut;
    private javax.swing.JLabel surnameOut;
    private javax.swing.JLabel tiOut;
    private javax.swing.JLabel tpOut;
    private javax.swing.JLabel transpoOut;
    private javax.swing.JLabel udOut;
    // End of variables declaration//GEN-END:variables
}
