/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Payroll_IFrame;

import static MAIN_FRAME.mainFrame.pname;
import static Payroll_IFrame.computeIFrame.bpOut1;
import static Payroll_IFrame.computeIFrame.designationOut1;
import static Payroll_IFrame.computeIFrame.dsrV;
import static Payroll_IFrame.computeIFrame.empIDout1;
import static Payroll_IFrame.computeIFrame.fnameOut1;
import static Payroll_IFrame.computeIFrame.month13L;
import static Payroll_IFrame.computeIFrame.saltypeV;
import static Payroll_IFrame.computeIFrame.surnameOut1;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.io.FileOutputStream;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Nanika
 */
public class MONTH13 extends javax.swing.JFrame {
    
    int bp=Integer.parseInt(bpOut1.getText());
    final DecimalFormat df = new DecimalFormat(".##");
        
    void display(){
        String st=saltypeV.getText();
        
        if(st.equals("SEMI-MONTHLY")){
            bp=bp*2;
            b1.setText(Integer.toString(bp));
            b2.setText(Integer.toString(bp));
            b3.setText(Integer.toString(bp));
            b4.setText(Integer.toString(bp));
            b5.setText(Integer.toString(bp));
            b6.setText(Integer.toString(bp));
            b7.setText(Integer.toString(bp));
            b8.setText(Integer.toString(bp));
            b9.setText(Integer.toString(bp));
            b10.setText(Integer.toString(bp));
            b11.setText(Integer.toString(bp));
            b12.setText(Integer.toString(bp));
        }
        else{
            b1.setText(Integer.toString(bp));
            b2.setText(Integer.toString(bp));
            b3.setText(Integer.toString(bp));
            b4.setText(Integer.toString(bp));
            b5.setText(Integer.toString(bp));
            b6.setText(Integer.toString(bp));
            b7.setText(Integer.toString(bp));
            b8.setText(Integer.toString(bp));
            b9.setText(Integer.toString(bp));
            b10.setText(Integer.toString(bp));
            b11.setText(Integer.toString(bp));
            b12.setText(Integer.toString(bp));
        }
        
        a1.setText("0");
        a2.setText("0");
        a3.setText("0");
        a4.setText("0");
        a5.setText("0");
        a6.setText("0");
        a7.setText("0");
        a8.setText("0");
        a9.setText("0");
        a10.setText("0");
        a11.setText("0");
        a12.setText("0");
        
       
    }
    
    String finalBP(int absent){
        double dr=Double.parseDouble(dsrV.getText());
        double deduc=absent*dr;
        return df.format(bp-deduc);
    }

    public MONTH13() {
        initComponents();
        
       display();
       df.setRoundingMode(RoundingMode.DOWN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        b1 = new javax.swing.JLabel();
        b7 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        b9 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        b10 = new javax.swing.JLabel();
        b11 = new javax.swing.JLabel();
        b5 = new javax.swing.JLabel();
        b12 = new javax.swing.JLabel();
        b8 = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        b6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jan = new javax.swing.JCheckBox();
        feb = new javax.swing.JCheckBox();
        mar = new javax.swing.JCheckBox();
        apr = new javax.swing.JCheckBox();
        aug = new javax.swing.JCheckBox();
        may = new javax.swing.JCheckBox();
        jun = new javax.swing.JCheckBox();
        jul = new javax.swing.JCheckBox();
        dec = new javax.swing.JCheckBox();
        sep = new javax.swing.JCheckBox();
        oct = new javax.swing.JCheckBox();
        nov = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        a3 = new javax.swing.JTextField();
        a11 = new javax.swing.JTextField();
        a8 = new javax.swing.JTextField();
        a2 = new javax.swing.JTextField();
        a7 = new javax.swing.JTextField();
        a4 = new javax.swing.JTextField();
        a12 = new javax.swing.JTextField();
        a9 = new javax.swing.JTextField();
        a5 = new javax.swing.JTextField();
        a1 = new javax.swing.JTextField();
        a6 = new javax.swing.JTextField();
        a10 = new javax.swing.JTextField();
        doneBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        month13Out = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jButton1.setText("COMPUTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Basic Salary", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 51, 0));

        b1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        b7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        b3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        b9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        b2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        b10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        b11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        b5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        b12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        b8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        b4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        b6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "MONTHS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 51, 0))); // NOI18N

        jan.setSelected(true);
        jan.setText("January");
        jan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jan.setBorderPainted(true);
        jan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jan.setHideActionText(true);
        jan.setIconTextGap(5);
        jan.setInheritsPopupMenu(true);
        jan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                janActionPerformed(evt);
            }
        });

        feb.setSelected(true);
        feb.setText("February");
        feb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        feb.setBorderPainted(true);
        feb.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        feb.setHideActionText(true);
        feb.setIconTextGap(5);
        feb.setInheritsPopupMenu(true);
        feb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                febActionPerformed(evt);
            }
        });

        mar.setSelected(true);
        mar.setText("March");
        mar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        mar.setBorderPainted(true);
        mar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mar.setHideActionText(true);
        mar.setIconTextGap(5);
        mar.setInheritsPopupMenu(true);
        mar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marActionPerformed(evt);
            }
        });

        apr.setSelected(true);
        apr.setText("April");
        apr.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        apr.setBorderPainted(true);
        apr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        apr.setHideActionText(true);
        apr.setIconTextGap(5);
        apr.setInheritsPopupMenu(true);
        apr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aprActionPerformed(evt);
            }
        });

        aug.setSelected(true);
        aug.setText("August");
        aug.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        aug.setBorderPainted(true);
        aug.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        aug.setHideActionText(true);
        aug.setIconTextGap(5);
        aug.setInheritsPopupMenu(true);
        aug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                augActionPerformed(evt);
            }
        });

        may.setSelected(true);
        may.setText("May");
        may.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        may.setBorderPainted(true);
        may.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        may.setHideActionText(true);
        may.setIconTextGap(5);
        may.setInheritsPopupMenu(true);
        may.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mayActionPerformed(evt);
            }
        });

        jun.setSelected(true);
        jun.setText("June");
        jun.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jun.setBorderPainted(true);
        jun.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jun.setHideActionText(true);
        jun.setIconTextGap(5);
        jun.setInheritsPopupMenu(true);
        jun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                junActionPerformed(evt);
            }
        });

        jul.setSelected(true);
        jul.setText("July");
        jul.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jul.setBorderPainted(true);
        jul.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jul.setHideActionText(true);
        jul.setIconTextGap(5);
        jul.setInheritsPopupMenu(true);
        jul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                julActionPerformed(evt);
            }
        });

        dec.setSelected(true);
        dec.setText("December");
        dec.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        dec.setBorderPainted(true);
        dec.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dec.setHideActionText(true);
        dec.setIconTextGap(5);
        dec.setInheritsPopupMenu(true);
        dec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decActionPerformed(evt);
            }
        });

        sep.setSelected(true);
        sep.setText("September");
        sep.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        sep.setBorderPainted(true);
        sep.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sep.setHideActionText(true);
        sep.setIconTextGap(5);
        sep.setInheritsPopupMenu(true);
        sep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sepActionPerformed(evt);
            }
        });

        oct.setSelected(true);
        oct.setText("October");
        oct.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        oct.setBorderPainted(true);
        oct.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        oct.setHideActionText(true);
        oct.setIconTextGap(5);
        oct.setInheritsPopupMenu(true);
        oct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                octActionPerformed(evt);
            }
        });

        nov.setSelected(true);
        nov.setText("November");
        nov.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        nov.setBorderPainted(true);
        nov.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nov.setHideActionText(true);
        nov.setIconTextGap(5);
        nov.setInheritsPopupMenu(true);
        nov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dec)
                    .addComponent(nov)
                    .addComponent(oct)
                    .addComponent(sep)
                    .addComponent(aug)
                    .addComponent(jul)
                    .addComponent(jun)
                    .addComponent(may)
                    .addComponent(apr)
                    .addComponent(mar)
                    .addComponent(feb))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {apr, aug, dec, feb, jan, jul, jun, mar, may, nov, oct, sep});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(feb)
                .addGap(7, 7, 7)
                .addComponent(mar)
                .addGap(7, 7, 7)
                .addComponent(apr)
                .addGap(7, 7, 7)
                .addComponent(may)
                .addGap(7, 7, 7)
                .addComponent(jun)
                .addGap(7, 7, 7)
                .addComponent(jul)
                .addGap(7, 7, 7)
                .addComponent(aug)
                .addGap(7, 7, 7)
                .addComponent(sep)
                .addGap(7, 7, 7)
                .addComponent(oct)
                .addGap(7, 7, 7)
                .addComponent(nov)
                .addGap(7, 7, 7)
                .addComponent(dec)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {apr, aug, dec, feb, jan, jul, jun, mar, may, nov, oct, sep});

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "No. of Absent w/o Pay", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 51, 0))); // NOI18N

        a3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });
        a3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                a3KeyReleased(evt);
            }
        });

        a11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                a11KeyReleased(evt);
            }
        });

        a8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                a8KeyReleased(evt);
            }
        });

        a2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });
        a2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                a2KeyReleased(evt);
            }
        });

        a7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a7ActionPerformed(evt);
            }
        });
        a7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                a7KeyReleased(evt);
            }
        });

        a4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                a4KeyReleased(evt);
            }
        });

        a12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                a12KeyReleased(evt);
            }
        });

        a9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                a9KeyReleased(evt);
            }
        });

        a5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a5ActionPerformed(evt);
            }
        });
        a5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                a5KeyReleased(evt);
            }
        });

        a1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                a1KeyReleased(evt);
            }
        });

        a6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                a6KeyReleased(evt);
            }
        });

        a10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a10ActionPerformed(evt);
            }
        });
        a10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                a10KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(a4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(a5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(a6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(a7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(a8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(a9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(a10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(a11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a12)
                .addContainerGap())
        );

        doneBtn.setText("Save");
        doneBtn.setEnabled(false);
        doneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneBtnActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));

        jLabel28.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("13th Month Pay Computation");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        month13Out.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        month13Out.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 5, 2, 5, new java.awt.Color(0, 0, 0)));

        jButton2.setText("PRINT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(month13Out, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(doneBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(month13Out, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(doneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a2ActionPerformed

    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a3ActionPerformed

    private void a5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a5ActionPerformed

    private void a7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a7ActionPerformed

    private void a10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a10ActionPerformed

    private void febActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_febActionPerformed
         b2.setText(Integer.toString(bp));
        
        if(feb.isSelected()==false){
            b2.setText("0");
            a2.setText("0");
        }
    }//GEN-LAST:event_febActionPerformed

    private void marActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marActionPerformed
       b3.setText(Integer.toString(bp));
        
        if(mar.isSelected()==false) {
            b3.setText("0");
            a3.setText("0");
        }
    }//GEN-LAST:event_marActionPerformed

    private void aprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aprActionPerformed
     b4.setText(Integer.toString(bp));
        
        if(apr.isSelected()==false){
            b4.setText("0");
            a4.setText("0");
        }
    }//GEN-LAST:event_aprActionPerformed

    private void augActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_augActionPerformed
       b8.setText(Integer.toString(bp));
        
        if(aug.isSelected()==false) {
            b8.setText("0");
            a8.setText("0");
        }
    }//GEN-LAST:event_augActionPerformed

    private void mayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mayActionPerformed
        b5.setText(Integer.toString(bp));
        
        if(may.isSelected()==false){
            b5.setText("0");
            a5.setText("0");
        }
    }//GEN-LAST:event_mayActionPerformed

    private void junActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_junActionPerformed
       b6.setText(Integer.toString(bp));
        
        if(jun.isSelected()==false) {
            b6.setText("0");
            a6.setText("0");
        }
    }//GEN-LAST:event_junActionPerformed

    private void julActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_julActionPerformed
       b7.setText(Integer.toString(bp));
        
        if(jul.isSelected()==false){
            b7.setText("0");
            a7.setText("0");
        }
    }//GEN-LAST:event_julActionPerformed

    private void decActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decActionPerformed
       b12.setText(Integer.toString(bp));
        
        if(dec.isSelected()==false){
            b12.setText("0");
            a12.setText("0");
        }
    }//GEN-LAST:event_decActionPerformed

    private void sepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sepActionPerformed
       b9.setText(Integer.toString(bp));
        
        if(sep.isSelected()==false){
            b9.setText("0");
            a9.setText("0");
        }
    }//GEN-LAST:event_sepActionPerformed

    private void octActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_octActionPerformed
      b10.setText(Integer.toString(bp));
        
        if(oct.isSelected()==false){
            b10.setText("0");
            a10.setText("0");
        }
    }//GEN-LAST:event_octActionPerformed

    private void novActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novActionPerformed
        b11.setText(Integer.toString(bp));
        
        if(nov.isSelected()==false){
            b11.setText("0");
            a11.setText("0");
        }
    }//GEN-LAST:event_novActionPerformed

    private void janActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_janActionPerformed
        b1.setText(Integer.toString(bp));
        
        if(jan.isSelected()==false) {
            b1.setText("0");
            a1.setText("0");
        }

    }//GEN-LAST:event_janActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double B1=Double.parseDouble(b1.getText());
        double B2=Double.parseDouble(b2.getText());
        double B3=Double.parseDouble(b3.getText());
        double B4=Double.parseDouble(b4.getText());
        double B5=Double.parseDouble(b5.getText());
        double B6=Double.parseDouble(b6.getText());
        double B7=Double.parseDouble(b7.getText());
        double B8=Double.parseDouble(b8.getText());
        double B9=Double.parseDouble(b9.getText());
        double B10=Double.parseDouble(b10.getText());
        double B11=Double.parseDouble(b11.getText());
        double B12=Double.parseDouble(b12.getText());
           
        double total=B1+B2+B3+B4+B5+B6+B7+B8+B9+B10+B11+B12;
        double month13=total/12;
        
        month13Out.setText(df.format(month13));
        doneBtn.setEnabled(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void a1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a1KeyReleased
        b1.setText(finalBP(Integer.parseInt(a1.getText())));
    }//GEN-LAST:event_a1KeyReleased

    private void a2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a2KeyReleased
        b2.setText((finalBP(Integer.parseInt(a2.getText()))));   
    }//GEN-LAST:event_a2KeyReleased

    private void a3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a3KeyReleased
        b3.setText((finalBP(Integer.parseInt(a3.getText()))));   
    }//GEN-LAST:event_a3KeyReleased

    private void a4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a4KeyReleased
        b4.setText((finalBP(Integer.parseInt(a4.getText()))));   
    }//GEN-LAST:event_a4KeyReleased

    private void a5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a5KeyReleased
        b5.setText((finalBP(Integer.parseInt(a5.getText()))));   
    }//GEN-LAST:event_a5KeyReleased

    private void a6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a6KeyReleased
        b6.setText((finalBP(Integer.parseInt(a6.getText()))));   
    }//GEN-LAST:event_a6KeyReleased

    private void a7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a7KeyReleased
        b7.setText((finalBP(Integer.parseInt(a7.getText()))));   
    }//GEN-LAST:event_a7KeyReleased

    private void a8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a8KeyReleased
        b8.setText((finalBP(Integer.parseInt(a8.getText()))));   
    }//GEN-LAST:event_a8KeyReleased

    private void a9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a9KeyReleased
        b9.setText((finalBP(Integer.parseInt(a9.getText()))));   
    }//GEN-LAST:event_a9KeyReleased

    private void a10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a10KeyReleased
        b10.setText((finalBP(Integer.parseInt(a10.getText()))));   
    }//GEN-LAST:event_a10KeyReleased

    private void a11KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a11KeyReleased
        b11.setText((finalBP(Integer.parseInt(a11.getText()))));   
    }//GEN-LAST:event_a11KeyReleased

    private void a12KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a12KeyReleased
        b12.setText((finalBP(Integer.parseInt(a12.getText()))));   
    }//GEN-LAST:event_a12KeyReleased

    private void doneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneBtnActionPerformed
        month13L.setText(month13Out.getText());
        dispose();
    }//GEN-LAST:event_doneBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
     double a=Double.parseDouble(b1.getText());
     double b=Double.parseDouble(b2.getText());
     double c=Double.parseDouble(b3.getText());
     double d=Double.parseDouble(b4.getText());
     double e=Double.parseDouble(b5.getText());
     double f=Double.parseDouble(b6.getText());
     double g=Double.parseDouble(b7.getText());
     double h=Double.parseDouble(b8.getText());
     double i=Double.parseDouble(b9.getText());
     double j=Double.parseDouble(b10.getText());
     double k=Double.parseDouble(b11.getText());
     double l=Double.parseDouble(b12.getText());
     
     double sum=a+b+c+d+e+f+g+h+i+j+k+l;
        
    try {
        Document document=new Document();
        PdfWriter.getInstance(document, new FileOutputStream("13thMonthPay.pdf"));
        document.setPageSize(PageSize.A4);
        document.open();
        
         
        PdfPTable table1=new PdfPTable(2);
        table1.setWidthPercentage(107);
        table1.setSpacingBefore(1);
        table1.getDefaultCell().setBorder(PdfPCell.NO_BORDER);
        com.itextpdf.text.Font lfont;
            
        lfont=FontFactory.getFont(FontFactory.COURIER,9 ,Font.PLAIN,BaseColor.BLACK);
            
            PdfPCell t1=new PdfPCell(new Paragraph("Company: GOD's WAY DIAGNOSTIC CENTER",lfont));
            PdfPCell t2=new PdfPCell(new Paragraph((new java.util.Date().toString()),lfont));
            
            PdfPCell l1=new PdfPCell(new Paragraph("Employee ID: "+empIDout1.getText()+"",lfont));
            PdfPCell l2=new PdfPCell(new Paragraph("",lfont));
            
            PdfPCell l3=new PdfPCell(new Paragraph("Employee Name: "+fnameOut1.getText()+" "+surnameOut1.getText()+"",lfont));
            PdfPCell l4=new PdfPCell(new Paragraph("",lfont));
            
            PdfPCell l5=new PdfPCell(new Paragraph("Postion: "+designationOut1.getText()+"",lfont));
            PdfPCell l6=new PdfPCell(new Paragraph(""));
        
            
            t1.setHorizontalAlignment(Element.ALIGN_LEFT);
            t2.setHorizontalAlignment(Element.ALIGN_RIGHT);
            l1.setHorizontalAlignment(Element.ALIGN_LEFT);
            l2.setHorizontalAlignment(Element.ALIGN_RIGHT);
            l3.setHorizontalAlignment(Element.ALIGN_LEFT);
            l4.setHorizontalAlignment(Element.ALIGN_RIGHT);
            l5.setHorizontalAlignment(Element.ALIGN_LEFT);
            l6.setHorizontalAlignment(Element.ALIGN_RIGHT);
            
            t1.setBorder(Rectangle.NO_BORDER);
            t2.setBorder(Rectangle.NO_BORDER);
            l1.setBorder(Rectangle.NO_BORDER);
            l2.setBorder(Rectangle.NO_BORDER);
            l3.setBorder(Rectangle.NO_BORDER);
            l4.setBorder(Rectangle.NO_BORDER);
            l5.setBorder(Rectangle.NO_BORDER);
            l6.setBorder(Rectangle.NO_BORDER);
            
            table1.addCell(t1);
            table1.addCell(t2);
            table1.addCell(l1);
            table1.addCell(l2);
            table1.addCell(l3);
            table1.addCell(l4);
            table1.addCell(l5);
            table1.addCell(l6);
            
            
            document.add(table1);
            
            PdfPTable table=new PdfPTable(4);
            table.getDefaultCell().setBorder(PdfPCell.NO_BORDER);
            table.setWidthPercentage(107);
            table.setWidths(new int[]{80,30,80,100});
            table.setSpacingAfter(15);
            table.setSpacingBefore(8);
            com.itextpdf.text.Font tfont;
            com.itextpdf.text.Font tfont1;
            com.itextpdf.text.Font tfont2;
            com.itextpdf.text.Font small;
            
            small=FontFactory.getFont(FontFactory.COURIER,6 ,Font.PLAIN,BaseColor.BLACK);
            tfont=FontFactory.getFont(FontFactory.COURIER,9 ,Font.PLAIN,BaseColor.BLACK);
            tfont1=FontFactory.getFont(FontFactory.COURIER_BOLD,11 ,Font.PLAIN,BaseColor.BLACK);
            tfont2=FontFactory.getFont(FontFactory.COURIER_BOLD,10 ,Font.PLAIN,BaseColor.BLACK);
            
            PdfPCell cell=new PdfPCell(new Paragraph("13th Month Pay",FontFactory.getFont(FontFactory.COURIER_BOLD,15 ,Font.PLAIN,BaseColor.WHITE)));
            cell.setColspan(4);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setBackgroundColor(BaseColor.DARK_GRAY);
            table.addCell(cell);
 
            PdfPCell cell1=new PdfPCell(new Paragraph("Months",tfont2));
            PdfPCell cell2=new PdfPCell(new Paragraph("Absents",tfont2));
            PdfPCell cell3=new PdfPCell(new Paragraph("Basic Pay",tfont2));
            PdfPCell cella=new PdfPCell(new Paragraph("",tfont));

            
            PdfPCell cell4=new PdfPCell(new Paragraph("January",tfont));
            PdfPCell cell5=new PdfPCell(new Paragraph(a1.getText(),tfont));
            PdfPCell cell6=new PdfPCell(new Paragraph(b1.getText(),tfont));
            PdfPCell cellb=new PdfPCell(new Paragraph("Received a sum of:",tfont));

            
            PdfPCell cell7=new PdfPCell(new Paragraph("February",tfont));
            PdfPCell cell8=new PdfPCell(new Paragraph(a2.getText(),tfont));
            PdfPCell cell9=new PdfPCell(new Paragraph(b2.getText(),tfont));
            PdfPCell cellc=new PdfPCell(new Paragraph("P "+month13Out.getText(),tfont2));

            
            PdfPCell cell10=new PdfPCell(new Paragraph("March",tfont));
            PdfPCell cell11=new PdfPCell(new Paragraph(a3.getText(),tfont));
            PdfPCell cell12=new PdfPCell(new Paragraph(b3.getText(),tfont));
            PdfPCell celld=new PdfPCell(new Paragraph("",tfont));
            
            PdfPCell cell13=new PdfPCell(new Paragraph("April",tfont));
            PdfPCell cell14=new PdfPCell(new Paragraph(a4.getText(),tfont));
            PdfPCell cell15=new PdfPCell(new Paragraph(b4.getText(),tfont));
            PdfPCell celle=new PdfPCell(new Paragraph("",tfont));
            
            PdfPCell cell16=new PdfPCell(new Paragraph("May",tfont));
            PdfPCell cell17=new PdfPCell(new Paragraph(a5.getText(),tfont));
            PdfPCell cell18=new PdfPCell(new Paragraph(b5.getText(),tfont));
            PdfPCell cellf=new PdfPCell(new Paragraph("",tfont));
            
            PdfPCell cell19=new PdfPCell(new Paragraph("June",tfont));
            PdfPCell cell20=new PdfPCell(new Paragraph(a6.getText(),tfont));
            PdfPCell cell21=new PdfPCell(new Paragraph(b6.getText(),tfont));
            PdfPCell cellg=new PdfPCell(new Paragraph("__________________",tfont));
            
            PdfPCell cell22=new PdfPCell(new Paragraph("July",tfont));
            PdfPCell cell23=new PdfPCell(new Paragraph(a7.getText(),tfont));
            PdfPCell cell24=new PdfPCell(new Paragraph(b7.getText(),tfont));
            PdfPCell cellh=new PdfPCell(new Paragraph("Signature",tfont));
            
            PdfPCell cell25=new PdfPCell(new Paragraph("August",tfont));
            PdfPCell cell26=new PdfPCell(new Paragraph(a8.getText(),tfont));
            PdfPCell cell27=new PdfPCell(new Paragraph(b8.getText(),tfont));
            PdfPCell celli=new PdfPCell(new Paragraph("",tfont));
            
            PdfPCell cell28=new PdfPCell(new Paragraph("September",tfont));
            PdfPCell cell29=new PdfPCell(new Paragraph(a9.getText(),tfont));
            PdfPCell cell30=new PdfPCell(new Paragraph(b9.getText(),tfont));
            PdfPCell cellj=new PdfPCell(new Paragraph("",tfont));
            
            PdfPCell cell31=new PdfPCell(new Paragraph("October",tfont));
            PdfPCell cell32=new PdfPCell(new Paragraph(a10.getText(),tfont));
            PdfPCell cell33=new PdfPCell(new Paragraph(b10.getText(),tfont));
            PdfPCell cellk=new PdfPCell(new Paragraph("",tfont));
            
            PdfPCell cell34=new PdfPCell(new Paragraph("November",tfont));
            PdfPCell cell35=new PdfPCell(new Paragraph(a11.getText(),tfont));
            PdfPCell cell36=new PdfPCell(new Paragraph(b11.getText(),tfont));
            PdfPCell celll=new PdfPCell(new Paragraph("",tfont));
            
            PdfPCell cell37=new PdfPCell(new Paragraph("December",tfont));
            PdfPCell cell38=new PdfPCell(new Paragraph(a12.getText(),tfont));
            PdfPCell cell39=new PdfPCell(new Paragraph(b12.getText(),tfont));
            PdfPCell cellm=new PdfPCell(new Paragraph("",tfont));
            
            PdfPCell cell40=new PdfPCell(new Paragraph("Total Salary Earned:",tfont2));
            cell40.setColspan(2);
            PdfPCell cell41=new PdfPCell(new Paragraph(df.format(sum) ,tfont2));
            PdfPCell celln=new PdfPCell(new Paragraph("",tfont));
            
            PdfPCell cell42=new PdfPCell(new Paragraph("Total 13th Month Pay: ",tfont2));
            cell42.setColspan(2);
            PdfPCell cell43=new PdfPCell(new Paragraph(month13Out.getText(),tfont2));
            PdfPCell cello=new PdfPCell(new Paragraph("",tfont2));
            
            
            cell1.setBorder(Rectangle.LEFT | Rectangle.BOTTOM );
            cell2.setBorder(Rectangle.LEFT | Rectangle.BOTTOM);
            cell3.setBorder(Rectangle.LEFT | Rectangle.BOTTOM);
            cella.setBorder(Rectangle.LEFT |Rectangle.RIGHT );
            
            cell4.setBorder(Rectangle.LEFT);
            cell5.setBorder(Rectangle.LEFT);
            cell6.setBorder(Rectangle.LEFT);
            cellb.setBorder(Rectangle.LEFT |Rectangle.RIGHT);
            
            cell7.setBorder(Rectangle.LEFT);
            cell8.setBorder(Rectangle.LEFT);
            cell9.setBorder(Rectangle.LEFT);
            cellc.setBorder(Rectangle.LEFT |Rectangle.RIGHT);
            
            cell10.setBorder(Rectangle.LEFT);
            cell11.setBorder(Rectangle.LEFT);
            cell12.setBorder(Rectangle.LEFT);
            celld.setBorder(Rectangle.LEFT |Rectangle.RIGHT);
            
            cell13.setBorder(Rectangle.LEFT);
            cell14.setBorder(Rectangle.LEFT);
            cell15.setBorder(Rectangle.LEFT);
            celle.setBorder(Rectangle.LEFT |Rectangle.RIGHT);
            
            cell16.setBorder(Rectangle.LEFT);
            cell17.setBorder(Rectangle.LEFT);
            cell18.setBorder(Rectangle.LEFT);
            cellf.setBorder(Rectangle.LEFT |Rectangle.RIGHT);
            
            cell19.setBorder(Rectangle.LEFT);
            cell20.setBorder(Rectangle.LEFT);
            cell21.setBorder(Rectangle.LEFT);
            cellg.setBorder(Rectangle.LEFT |Rectangle.RIGHT);
            
            cell22.setBorder(Rectangle.LEFT);
            cell23.setBorder(Rectangle.LEFT);
            cell24.setBorder(Rectangle.LEFT);
            cellh.setBorder(Rectangle.LEFT |Rectangle.RIGHT);
            
            cell25.setBorder(Rectangle.LEFT);
            cell26.setBorder(Rectangle.LEFT);
            cell7.setBorder(Rectangle.LEFT);
            celli.setBorder(Rectangle.LEFT |Rectangle.RIGHT);
            
            cell25.setBorder(Rectangle.LEFT);
            cell26.setBorder(Rectangle.LEFT);
            cell27.setBorder(Rectangle.LEFT);
            celli.setBorder(Rectangle.LEFT |Rectangle.RIGHT);
            
            cell28.setBorder(Rectangle.LEFT);
            cell29.setBorder(Rectangle.LEFT);
            cell30.setBorder(Rectangle.LEFT);
            cellj.setBorder(Rectangle.LEFT |Rectangle.RIGHT);
            
            cell31.setBorder(Rectangle.LEFT);
            cell32.setBorder(Rectangle.LEFT);
            cell33.setBorder(Rectangle.LEFT);
            cellk.setBorder(Rectangle.LEFT |Rectangle.RIGHT);
            
            cell34.setBorder(Rectangle.LEFT);
            cell35.setBorder(Rectangle.LEFT);
            cell36.setBorder(Rectangle.LEFT);
            celll.setBorder(Rectangle.LEFT |Rectangle.RIGHT);
            
            cell37.setBorder(Rectangle.LEFT);
            cell38.setBorder(Rectangle.LEFT);
            cell39.setBorder(Rectangle.LEFT);
            cellm.setBorder(Rectangle.LEFT |Rectangle.RIGHT);
            
            celln.setBorder(Rectangle.LEFT | Rectangle.RIGHT );
            cello.setBorder(Rectangle.LEFT | Rectangle.RIGHT | Rectangle.BOTTOM);
            
            
            cell1.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell2.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell3.setHorizontalAlignment(Element.ALIGN_CENTER);
            cella.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            cell4.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell5.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell6.setHorizontalAlignment(Element.ALIGN_CENTER);
            cellb.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            cell7.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell8.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell9.setHorizontalAlignment(Element.ALIGN_CENTER);
            cellc.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            cell10.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell11.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell12.setHorizontalAlignment(Element.ALIGN_CENTER);
            celld.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            cell13.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell14.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell15.setHorizontalAlignment(Element.ALIGN_CENTER);
            celle.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            cell16.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell17.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell18.setHorizontalAlignment(Element.ALIGN_CENTER);
            cellf.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            cell19.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell20.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell21.setHorizontalAlignment(Element.ALIGN_CENTER);
            cellg.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            cell22.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell23.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell24.setHorizontalAlignment(Element.ALIGN_CENTER);
            cellh.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            cell25.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell26.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell27.setHorizontalAlignment(Element.ALIGN_CENTER);
            celli.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            cell28.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell29.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell30.setHorizontalAlignment(Element.ALIGN_CENTER);
            cellj.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            cell31.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell32.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell33.setHorizontalAlignment(Element.ALIGN_CENTER);
            cellk.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            cell34.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell35.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell36.setHorizontalAlignment(Element.ALIGN_CENTER);
            celll.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            cell37.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell38.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell39.setHorizontalAlignment(Element.ALIGN_CENTER);
            cellm.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            cell40.setHorizontalAlignment(Element.ALIGN_RIGHT);
            cell41.setHorizontalAlignment(Element.ALIGN_CENTER);
            celln.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            cell42.setHorizontalAlignment(Element.ALIGN_RIGHT);
            cell43.setHorizontalAlignment(Element.ALIGN_CENTER);
            cello.setHorizontalAlignment(Element.ALIGN_CENTER);
                    
            
            table.addCell(cell1);
            table.addCell(cell2);
            table.addCell(cell3);
            table.addCell(cella);
            
            table.addCell(cell4);
            table.addCell(cell5);
            table.addCell(cell6);
            table.addCell(cellb);
            
            table.addCell(cell7);
            table.addCell(cell8);
            table.addCell(cell9);
            table.addCell(cellc);
            
            table.addCell(cell10);
            table.addCell(cell11);
            table.addCell(cell12);
            table.addCell(celld);
            
            table.addCell(cell13);
            table.addCell(cell14);
            table.addCell(cell15);
            table.addCell(celle);
            
            table.addCell(cell16);
            table.addCell(cell17);
            table.addCell(cell18);
            table.addCell(cellf);
            
            table.addCell(cell19);
            table.addCell(cell20);
            table.addCell(cell21);
            table.addCell(cellg);
            
            table.addCell(cell22);
            table.addCell(cell23);
            table.addCell(cell24);
            table.addCell(cellh);
            
            table.addCell(cell25);
            table.addCell(cell26);
            table.addCell(cell27);
            table.addCell(celli);
            
            table.addCell(cell28);
            table.addCell(cell29);
            table.addCell(cell30);
            table.addCell(cellj);
            
            table.addCell(cell31);
            table.addCell(cell32);
            table.addCell(cell33);
            table.addCell(cellk);
            
            table.addCell(cell34);
            table.addCell(cell35);
            table.addCell(cell36);
            table.addCell(celll);
            
            table.addCell(cell37);
            table.addCell(cell38);
            table.addCell(cell39);
            table.addCell(cellm);
            
            table.addCell(cell40);
            table.addCell(cell41);
            table.addCell(celln);
            
            table.addCell(cell42);
            table.addCell(cell43);
            table.addCell(cello);

            document.add(table);        
        
        PdfPTable signs=new PdfPTable(2);
        signs.setWidthPercentage(107);
        signs.setSpacingBefore(0);
        signs.getDefaultCell().setBorder(PdfPCell.NO_BORDER);
            
        
            PdfPCell s1=new PdfPCell(new Paragraph("Manager's Signature:____________________",lfont));
            PdfPCell s2=new PdfPCell(new Paragraph("Prepared By: "+pname.getText()+"",lfont));

            
            s1.setHorizontalAlignment(Element.ALIGN_LEFT);
            s2.setHorizontalAlignment(Element.ALIGN_RIGHT);
            
            s1.setBorder(Rectangle.NO_BORDER);
            s2.setBorder(Rectangle.NO_BORDER);

            signs.addCell(s1);
            signs.addCell(s2);
            
            document.add(signs);
            
                   
      
        document.close();
        
        try{
             Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"C:\\Program Files\\EZPayroll\\13thMonthPay.pdf");
             
         }
         catch (Exception ex){
             JOptionPane.showMessageDialog(null,ex);
         }
        
        }        
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MONTH13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MONTH13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MONTH13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MONTH13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MONTH13().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a10;
    private javax.swing.JTextField a11;
    private javax.swing.JTextField a12;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField a4;
    private javax.swing.JTextField a5;
    private javax.swing.JTextField a6;
    private javax.swing.JTextField a7;
    private javax.swing.JTextField a8;
    private javax.swing.JTextField a9;
    private javax.swing.JCheckBox apr;
    private javax.swing.JCheckBox aug;
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b10;
    private javax.swing.JLabel b11;
    private javax.swing.JLabel b12;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JLabel b5;
    private javax.swing.JLabel b6;
    private javax.swing.JLabel b7;
    private javax.swing.JLabel b8;
    private javax.swing.JLabel b9;
    private javax.swing.JCheckBox dec;
    private javax.swing.JButton doneBtn;
    private javax.swing.JCheckBox feb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JCheckBox jan;
    private javax.swing.JCheckBox jul;
    private javax.swing.JCheckBox jun;
    private javax.swing.JCheckBox mar;
    private javax.swing.JCheckBox may;
    private javax.swing.JLabel month13Out;
    private javax.swing.JCheckBox nov;
    private javax.swing.JCheckBox oct;
    private javax.swing.JCheckBox sep;
    // End of variables declaration//GEN-END:variables
}
