/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Payroll_IFrame;

import static Payroll_IFrame.searchP.table;
import java.math.RoundingMode;
import java.sql.*;
import java.text.DecimalFormat;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author TRAINEE
 */
public class SalmgmtIFrame extends javax.swing.JInternalFrame {

    ResultSet rs=null;
    PreparedStatement pst=null;
    Connection conn=null;
    Statement stmt=null;
    searchP p1;
    static double bp,wd;
    
    final DecimalFormat df = new DecimalFormat(".##");
    
    
    public void openConnection(){
        try {
            Class.forName("org.h2.Driver");
            conn = DriverManager.getConnection("jdbc:h2:~/Peeroll;IGNORECASE=TRUE","edmon", "" );
        }
         catch( Exception e )
        {
            JOptionPane.showMessageDialog(null, "PROGRAM ALREADY IN USE.");
        }
    }
    
    public SalmgmtIFrame() {
        initComponents();
        df.setRoundingMode(RoundingMode.DOWN);
        
        openConnection();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        foodIn = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        sal = new javax.swing.JLabel();
        bpIn = new javax.swing.JTextField();
        transpoIn = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        dsrIn = new javax.swing.JTextField();
        msrIn = new javax.swing.JTextField();
        hsrIn = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        salType = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        leavecIn = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        depIn = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        pagibigIn = new javax.swing.JTextField();
        philhealthIn = new javax.swing.JTextField();
        sssIn = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        wdIn = new javax.swing.JTextField();
        philhealthT = new javax.swing.JLabel();
        pagibigT = new javax.swing.JLabel();
        sssT = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        bpOut = new javax.swing.JLabel();
        dsrOut = new javax.swing.JLabel();
        hsrOut = new javax.swing.JLabel();
        msrOut = new javax.swing.JLabel();
        foodOut = new javax.swing.JLabel();
        transpoOut = new javax.swing.JLabel();
        philhealthOut = new javax.swing.JLabel();
        sssOut = new javax.swing.JLabel();
        pagibigOut = new javax.swing.JLabel();
        designationOut = new javax.swing.JLabel();
        cont = new javax.swing.JLabel();
        fnameOut = new javax.swing.JLabel();
        surnameOut = new javax.swing.JLabel();
        empIDout = new javax.swing.JLabel();
        deptOut = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        picOut = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        saveBtn1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(1012, 630));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true), "SET EMPLOYEE SALARY", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB", 0, 18), new java.awt.Color(51, 51, 51))); // NOI18N

        jLabel7.setText("Daily Salary Rate:");

        foodIn.setEnabled(false);
        foodIn.setMinimumSize(new java.awt.Dimension(2, 20));
        foodIn.setPreferredSize(new java.awt.Dimension(2, 20));

        jLabel20.setText("Food Allowances:");

        jLabel18.setText("Hourly Salary Rate:");

        sal.setText("Monthly Salary:");

        bpIn.setEnabled(false);
        bpIn.setMinimumSize(new java.awt.Dimension(2, 20));
        bpIn.setPreferredSize(new java.awt.Dimension(2, 20));
        bpIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpInActionPerformed(evt);
            }
        });
        bpIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bpInKeyReleased(evt);
            }
        });

        transpoIn.setEnabled(false);
        transpoIn.setMinimumSize(new java.awt.Dimension(2, 20));
        transpoIn.setPreferredSize(new java.awt.Dimension(2, 20));
        transpoIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transpoInActionPerformed(evt);
            }
        });

        jLabel21.setText("Transportation Allowances:");

        dsrIn.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        dsrIn.setEnabled(false);
        dsrIn.setMinimumSize(new java.awt.Dimension(2, 20));
        dsrIn.setPreferredSize(new java.awt.Dimension(2, 20));
        dsrIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsrInActionPerformed(evt);
            }
        });

        msrIn.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        msrIn.setEnabled(false);
        msrIn.setMinimumSize(new java.awt.Dimension(2, 20));
        msrIn.setPreferredSize(new java.awt.Dimension(2, 20));
        msrIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msrInActionPerformed(evt);
            }
        });

        hsrIn.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        hsrIn.setEnabled(false);
        hsrIn.setMinimumSize(new java.awt.Dimension(2, 20));
        hsrIn.setPreferredSize(new java.awt.Dimension(2, 20));
        hsrIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hsrInActionPerformed(evt);
            }
        });

        jLabel19.setText("Minute Salary Rate:");

        jLabel5.setText("Working days in a year:");

        jLabel6.setText("Salary Type:");

        salType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SEMI-MONTHLY", "MONTHLY", "WEEKLY", "DAILY", "", "" }));
        salType.setEnabled(false);
        salType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salTypeActionPerformed(evt);
            }
        });

        jLabel25.setText("Leave Count:");

        leavecIn.setEnabled(false);
        leavecIn.setMinimumSize(new java.awt.Dimension(2, 20));
        leavecIn.setPreferredSize(new java.awt.Dimension(2, 20));

        jLabel26.setText("Dependents:");

        depIn.setText("0");
        depIn.setEnabled(false);
        depIn.setMinimumSize(new java.awt.Dimension(2, 20));
        depIn.setPreferredSize(new java.awt.Dimension(2, 20));

        jLabel23.setText("PAGIBIG Contribution:");

        pagibigIn.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        pagibigIn.setEnabled(false);
        pagibigIn.setMinimumSize(new java.awt.Dimension(2, 20));
        pagibigIn.setPreferredSize(new java.awt.Dimension(2, 20));

        philhealthIn.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        philhealthIn.setEnabled(false);
        philhealthIn.setMinimumSize(new java.awt.Dimension(2, 20));
        philhealthIn.setPreferredSize(new java.awt.Dimension(2, 20));
        philhealthIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                philhealthInActionPerformed(evt);
            }
        });

        sssIn.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        sssIn.setEnabled(false);
        sssIn.setMinimumSize(new java.awt.Dimension(2, 20));
        sssIn.setPreferredSize(new java.awt.Dimension(2, 20));

        jLabel24.setText("SSS Contribution:");

        jLabel22.setText("PHILHEALTH Contributions:");

        wdIn.setToolTipText("313 for Mon-Sat 262 for Mon-Fri");
        wdIn.setEnabled(false);

        philhealthT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESOURCES/phic-logo.jpg"))); // NOI18N
        philhealthT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        philhealthT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                philhealthTMouseClicked(evt);
            }
        });

        pagibigT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESOURCES/pagibiglogo.png"))); // NOI18N
        pagibigT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pagibigT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pagibigTMouseClicked(evt);
            }
        });

        sssT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESOURCES/SSS_logo_PH.svg.png"))); // NOI18N
        sssT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sssT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sssTMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(salType, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel5)
                        .addGap(20, 20, 20)
                        .addComponent(wdIn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(sal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bpIn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(dsrIn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(hsrIn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(msrIn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(foodIn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(transpoIn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(leavecIn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(depIn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(pagibigIn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(pagibigT))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(philhealthIn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(philhealthT))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(sssIn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(sssT)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(salType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(wdIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sal)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(bpIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7))
                    .addComponent(dsrIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel18))
                    .addComponent(hsrIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel19))
                    .addComponent(msrIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel20))
                    .addComponent(foodIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel21))
                    .addComponent(transpoIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel25))
                    .addComponent(leavecIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel26))
                    .addComponent(depIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pagibigIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(pagibigT, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel22))
                    .addComponent(philhealthIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(philhealthT))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel24))
                    .addComponent(sssIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(sssT)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true), "EMPLOYEE SALARY PROFILE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Berlin Sans FB", 0, 18), new java.awt.Color(51, 51, 51))); // NOI18N

        jLabel3.setText("Name:");

        jLabel12.setText("Employee ID:");

        jLabel13.setText("Designation:");

        jLabel27.setText("Department:");

        jLabel36.setText("Basic Salary:");

        jLabel37.setText("Daily Salary Rate:");

        jLabel38.setText("Hourly Salary Rate:");

        jLabel39.setText("Minute Salary Rate:");

        jLabel40.setText("Food Allowances:");

        jLabel41.setText("Transpo Allowance:");

        jLabel42.setText("PHILHEALTH:");

        jLabel43.setText("PAG-BIG:");

        jLabel44.setText("SSS:");

        bpOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bpOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        dsrOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dsrOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        hsrOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hsrOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        msrOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msrOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        foodOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foodOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        transpoOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transpoOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        philhealthOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        philhealthOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        sssOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sssOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pagibigOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pagibigOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        designationOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        designationOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cont.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cont.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        empIDout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empIDout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        deptOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deptOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jDesktopPane1.setBackground(new java.awt.Color(240, 240, 240));

        picOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jDesktopPane1.setLayer(picOut, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(picOut, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(picOut, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bpOut, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dsrOut, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hsrOut, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(msrOut, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(foodOut, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transpoOut, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel44)
                        .addGap(11, 11, 11)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(philhealthOut, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pagibigOut, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sssOut, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel13)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(empIDout, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(surnameOut, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fnameOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cont, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deptOut, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(designationOut, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(empIDout, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(surnameOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fnameOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cont, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(deptOut, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(designationOut, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel36)
                    .addComponent(bpOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(philhealthOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addComponent(dsrOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel38))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(hsrOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addGap(6, 6, 6))
                            .addComponent(msrOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pagibigOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel44)
                            .addComponent(sssOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(foodOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41)
                    .addComponent(transpoOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        search.setText("FIND EMPLOYEE");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESOURCES/Find User Male.png"))); // NOI18N

        editButton.setText("EDIT");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESOURCES/Edit User Male_2.png"))); // NOI18N

        saveBtn1.setText("SAVE");
        saveBtn1.setEnabled(false);
        saveBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtn1ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESOURCES/Save.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("SALARY MANAGEMENT");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(366, 366, 366))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        cancelBtn.setText("CANCEL");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESOURCES/Clear Symbol.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel4)
                .addGap(0, 0, 0)
                .addComponent(saveBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel28)
                .addGap(10, 10, 10)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel30)
                .addGap(0, 0, 0)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(saveBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void philhealthInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_philhealthInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_philhealthInActionPerformed

    private void transpoInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transpoInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transpoInActionPerformed

    private void dsrInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsrInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dsrInActionPerformed

    private void msrInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msrInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msrInActionPerformed

    private void hsrInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hsrInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hsrInActionPerformed

    private void saveBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtn1ActionPerformed
        String test=depIn.getText();
        String test1=foodIn.getText();
        String test2=transpoIn.getText();
        String test3=leavecIn.getText();
        String test4=pagibigIn.getText();
        String test5=philhealthIn.getText();
        String test6=sssIn.getText();
                
        
        if(test.equals("")) depIn.setText("0");
        if(test1.equals("")) foodIn.setText("0");
        if(test2.equals("")) transpoIn.setText("0");
        if(test3.equals("")) leavecIn.setText("0");
        if(test4.equals("")) pagibigIn.setText("0");
        if(test5.equals("")) philhealthIn.setText("0");
        if(test6.equals("")) sssIn.setText("0");
        
        int row=table.getSelectedRow();
        String table_click=(table.getModel().getValueAt(row, 0).toString());

        try{
             
            String query="UPDATE EMPdata SET empid='"+empIDout.getText()+"',surname='"+surnameOut.getText()+"',firstname='"+fnameOut.getText()+"',designation='"+designationOut.getText()+"',department='"+deptOut.getText()+"', bp='"+bpIn.getText()+"',food='"+foodIn.getText()+"',transpo='"+transpoIn.getText()+"',pagibig='"+philhealthIn.getText()+"',sss='"+sssIn.getText()+"',philhealth='"+pagibigIn.getText()+"' ,leavec='"+leavecIn.getText()+"' ,dependents='"+depIn.getText()+"' ,saltype='"+salType.getSelectedItem()+"' ,wd='"+wdIn.getText()+"', dsr='"+dsrIn.getText()+"', hsr='"+hsrIn.getText()+"', msr='"+msrIn.getText()+"' where empid='"+table_click+"'";
            pst=conn.prepareStatement(query);
            
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"EMPLOYEE DATA ADDED");
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        bpOut.setText(bpIn.getText());
        foodOut.setText(foodIn.getText());

        transpoOut.setText(transpoIn.getText());
        pagibigOut.setText(pagibigIn.getText());
        sssOut.setText(sssIn.getText());
        philhealthOut.setText(philhealthIn.getText());
        dsrOut.setText(dsrIn.getText());
        hsrOut.setText(hsrIn.getText());
        msrOut.setText(msrIn.getText());
        
        wdIn.setEnabled(false);
        bpIn.setEnabled(false);
        depIn.setEnabled(false);
        foodIn.setEnabled(false);
        transpoIn.setEnabled(false);
        leavecIn.setEnabled(false);
        pagibigIn.setEnabled(false);
        philhealthIn.setEnabled(false);
        sssIn.setEnabled(false);

    }//GEN-LAST:event_saveBtn1ActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        saveBtn1.setEnabled(true);
        String weekly=(String) salType.getSelectedItem();
        if(empIDout.getText().equals("")){
            JOptionPane.showMessageDialog(null, "PLEASE SELECT AN EMPLOYEE.");
        }
        else{
        if(!weekly.equals("WEEKLY")){
            wdIn.setEnabled(true);
        }
        salType.setEnabled(true);
        foodIn.setEnabled(true);
        transpoIn.setEnabled(true);
        leavecIn.setEnabled(true);
        depIn.setEnabled(true);
        bpIn.setEnabled(true);
        pagibigIn.setEnabled(true);
        philhealthIn.setEnabled(true);
        sssIn.setEnabled(true);
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
       p1=new searchP(); 
       p1.setVisible(true);
    }//GEN-LAST:event_searchActionPerformed

    private void bpInKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bpInKeyReleased
        String daily=(String)salType.getSelectedItem();
        
        if(wdIn.getText().equals("") && !daily.equals("WEEKLY")){
            JOptionPane.showMessageDialog(null,"ENTER NUMBER OF WORKING DAYS/YR.");    
        }
        if(!daily.equals("WEEKLY")) wd=Double.parseDouble(wdIn.getText());
        bp=Double.parseDouble(bpIn.getText());
        
        if(daily.equals("WEEKLY")){
            double DSRT=bp/6;

            double HSRT=DSRT/8;

            double MSRT=HSRT/60;

            dsrIn.setText(df.format(DSRT));
            hsrIn.setText(df.format(HSRT));
            msrIn.setText(df.format(MSRT));
            
        }
        else{
            double DSRT=bp*12/wd;

            double HSRT=DSRT/8;

            double MSRT=HSRT/60;

            dsrIn.setText(df.format(DSRT));
            hsrIn.setText(df.format(HSRT));
            msrIn.setText(df.format(MSRT));

            if(bp<=8999){
                philhealthIn.setText("100");
            }
            else if(bp>=9000 && bp<=9999.99){
                philhealthIn.setText("112.50");
            }
            else if(bp>=10000 && bp<=10999.99){
                philhealthIn.setText("125");
            }

            else if(bp>=11000 && bp<=11999.99){
                philhealthIn.setText("137.50");
            }
            else if(bp>=12000 && bp<=12999.99){
                philhealthIn.setText("150.00");
            }
            else if(bp>=13000 && bp<=13999.99){
                philhealthIn.setText("162.50");
            }
            else if(bp>=14000 && bp<=14999.99){
                philhealthIn.setText("175.00");
            }
            else if(bp>=15000 && bp<=15999.99){
                philhealthIn.setText("187.50");
            }
            else if(bp>=16000 && bp<=16999.99){
                philhealthIn.setText("200");
            }
            else if(bp>=17000 && bp<=17999.99){
                philhealthIn.setText("212.50");
            }
            else if(bp>=18000 && bp<=18999.99){
                philhealthIn.setText("225");
            }
            else if(bp>=19000 && bp<=19999.99){
                philhealthIn.setText("237.50");
            }
            else if(bp>=20000 && bp<=20999.99){
                philhealthIn.setText("250");
            }
            else if(bp>=21000 && bp<=21999.99){
                philhealthIn.setText("262.50");
            }
            else if(bp>=22000 && bp<=22999.99){
                philhealthIn.setText("275");
            }
            else if(bp>=23000 && bp<=23999.99){
                philhealthIn.setText("287.50");
            }
            else if(bp>=24000 && bp<=24999.99){
                philhealthIn.setText("300");
            }
            else if(bp>=25000 && bp<=25999.99){
                philhealthIn.setText("312.50");
            }
            else if(bp>=26000 && bp<=26999.99){
                philhealthIn.setText("325");
            }
            else if(bp>=27000 && bp<=27999.99){
                philhealthIn.setText("337.50");
            }
            else if(bp>=28000 && bp<=28999.99){
                philhealthIn.setText("350");
            }
            else if(bp>=29000 && bp<=29999.99){
                philhealthIn.setText("362.50");
            }
            else if(bp>=30000 && bp<=30999.99){
                philhealthIn.setText("375");
            }
            else if(bp>=31000 && bp<=31999.99){
                philhealthIn.setText("387.50");
            }
            else if(bp>=32000 && bp<=32999.99){
                philhealthIn.setText("400");
            }
            else if(bp>=33000 && bp<=33999.99){
                philhealthIn.setText("412.50");
            }
            else if(bp>=34000 && bp<=34999.99){
                philhealthIn.setText("425");
            }
            else if(bp>=35000){
                philhealthIn.setText("437.50");
            }
            //END OF PHILHEALTH COMPU

            if(bp>=1000 && bp<=1249.99){
                sssIn.setText("36.30");
            }
            else if(bp>=1250 && bp<=1749.99){
                sssIn.setText("54.50");
            }
            else if(bp>=1750 && bp<=2249.99){
                sssIn.setText("72.70");
            }
            else if(bp>=2250 && bp<=2749.99){
                sssIn.setText("90.80");
            }
            else if(bp>=2750 && bp<=3249.99){
                sssIn.setText("109");
            }
            else if(bp>=3250 && bp<=3749.99){
                sssIn.setText("127.20");
            }
            else if(bp>=3750 && bp<=4249.99){
                sssIn.setText("145.30");
            }
            else if(bp>=4250 && bp<=4749.99){
                sssIn.setText("163.50");
            }
            else if(bp>=4750 && bp<=5249.99){
                sssIn.setText("181.70");
            }
            else if(bp>=5250 && bp<=5749.99){
                sssIn.setText("199.80");
            }
            else if(bp>=5750 && bp<=6249.99){
                sssIn.setText("218");
            }
            else if(bp>=6250 && bp<=6749.99){
                sssIn.setText("236.20");
            }
            else if(bp>=6750 && bp<=7249.99){
                sssIn.setText("254.30");
            }
            else if(bp>=7250 && bp<=7749.99){
                sssIn.setText("272.50");
            }
            else if(bp>=7750 && bp<=8249.99){
                sssIn.setText("290.70");
            }
            else if(bp>=8250 && bp<=8749.99){
                sssIn.setText("308.80");
            }
            else if(bp>=8750 && bp<=9249.99){
                sssIn.setText("327");
            }
            else if(bp>=9250 && bp<=9749.99){
                sssIn.setText("345.20");
            }
            else if(bp>=9750 && bp<=10249.99){
                sssIn.setText("363.30");
            }
            else if(bp>=10250 && bp<=10749.99){
                sssIn.setText("381.50");
            }
            else if(bp>=10750 && bp<=11249.99){
                sssIn.setText("399.70");
            }
            else if(bp>=11250 && bp<=11749.99){
                sssIn.setText("417.80");
            }
            else if(bp>=11750 && bp<=12249.99){
                sssIn.setText("436");
            }
            else if(bp>=12250 && bp<=12749.99){
                sssIn.setText("454.20");
            }
            else if(bp>=12750 && bp<=13249.99){
                sssIn.setText("472.30");
            }
            else if(bp>=13250 && bp<=13749.99){
                sssIn.setText("490.50");
            }
            else if(bp>=13750 && bp<=14249.99){
                sssIn.setText("508.70");
            }
            else if(bp>=14250 && bp<=14749.99){
                sssIn.setText("526.80");
            }
            else if(bp>=14750 && bp<=15249.99){
                sssIn.setText("545.00");
            }
            else if(bp>=15250 && bp<=15749.99){
                sssIn.setText("563.20");
            }
            else if (bp>=15750){
                sssIn.setText("581.30");
            }
            //EMD OF SSS CONTRI COMPUTATION

            double pagibigcontri=0;

            if(bp<=1500){
                pagibigcontri=bp*0.01;
                pagibigIn.setText(Double.toString(pagibigcontri));
            }
            else if(bp>1500 && bp<=5000){
                pagibigcontri=bp*0.02;
                pagibigIn.setText(Double.toString(pagibigcontri));
            }
            else{
                pagibigIn.setText("100");
            }
        }
        
        
        
        
    }//GEN-LAST:event_bpInKeyReleased

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        saveBtn1.setEnabled(false);
        
        wdIn.setText("");
        salType.setSelectedItem(null);
        foodIn.setText("");
        transpoIn.setText("");
        leavecIn.setText("");
        depIn.setText("");
        bpIn.setText("");
        pagibigIn.setText("");
        philhealthIn.setText("");
        sssIn.setText("");
        dsrIn.setText("");
        hsrIn.setText("");
        msrIn.setText("");
        
        empIDout.setText("");
        fnameOut.setText("");
        surnameOut.setText("");
        designationOut.setText("");
        deptOut.setText("");
        bpOut.setText("");
        dsrOut.setText("");
        msrOut.setText("");
        hsrOut.setText("");
        foodOut.setText("");
        transpoOut.setText("");
        philhealthOut.setText("");
        pagibigOut.setText("");
        sssOut.setText("");
        picOut.setIcon(null);
        
        
        wdIn.setEnabled(false);
        salType.setEnabled(false);
        foodIn.setEnabled(false);
        transpoIn.setEnabled(false);
        leavecIn.setEnabled(false);
        depIn.setEnabled(false);
        bpIn.setEnabled(false);
        pagibigIn.setEnabled(false);
        philhealthIn.setEnabled(false);
        sssIn.setEnabled(false);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void pagibigTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagibigTMouseClicked
        try{
             Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"C:\\Program Files\\EZPayroll\\pagibigT.png");
             
         }
         catch (Exception ex){
             JOptionPane.showMessageDialog(null,ex);
         }    
    }//GEN-LAST:event_pagibigTMouseClicked

    private void philhealthTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_philhealthTMouseClicked
        try{
             Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"C:\\Program Files\\EZPayroll\\philhealthT.png");
             
         }
         catch (Exception ex){
             JOptionPane.showMessageDialog(null,ex);
         }  
    }//GEN-LAST:event_philhealthTMouseClicked

    private void sssTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sssTMouseClicked
        try{
             Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"C:\\Program Files\\EZPayroll\\sssT.png");
             
         }
         catch (Exception ex){
             JOptionPane.showMessageDialog(null,ex);
         } 
    }//GEN-LAST:event_sssTMouseClicked

    private void bpInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bpInActionPerformed

    private void salTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salTypeActionPerformed
        String selected=(String)salType.getSelectedItem();
        
        if(selected.equals("WEEKLY")){
           sal.setText("Weekly Salary:");
           wdIn.setEnabled(false);
           
        }
        else if(selected.equals("SEMI-MONTHLY") || selected.equals("MONTHLY") ){
           sal.setText("Monthly Salary:");
           wdIn.setEnabled(true);
        }
    }//GEN-LAST:event_salTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField bpIn;
    public static javax.swing.JLabel bpOut;
    private javax.swing.JButton cancelBtn;
    public static javax.swing.JLabel cont;
    public static javax.swing.JTextField depIn;
    public static javax.swing.JLabel deptOut;
    public static javax.swing.JLabel designationOut;
    public static javax.swing.JTextField dsrIn;
    public static javax.swing.JLabel dsrOut;
    private javax.swing.JButton editButton;
    public static javax.swing.JLabel empIDout;
    public static javax.swing.JLabel fnameOut;
    public static javax.swing.JTextField foodIn;
    public static javax.swing.JLabel foodOut;
    public static javax.swing.JTextField hsrIn;
    public static javax.swing.JLabel hsrOut;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JTextField leavecIn;
    public static javax.swing.JTextField msrIn;
    public static javax.swing.JLabel msrOut;
    public static javax.swing.JTextField pagibigIn;
    public static javax.swing.JLabel pagibigOut;
    private javax.swing.JLabel pagibigT;
    public static javax.swing.JTextField philhealthIn;
    public static javax.swing.JLabel philhealthOut;
    private javax.swing.JLabel philhealthT;
    public static javax.swing.JLabel picOut;
    private javax.swing.JLabel sal;
    public static javax.swing.JComboBox salType;
    public static javax.swing.JButton saveBtn1;
    private javax.swing.JButton search;
    public static javax.swing.JTextField sssIn;
    public static javax.swing.JLabel sssOut;
    private javax.swing.JLabel sssT;
    public static javax.swing.JLabel surnameOut;
    public static javax.swing.JTextField transpoIn;
    public static javax.swing.JLabel transpoOut;
    public static javax.swing.JTextField wdIn;
    // End of variables declaration//GEN-END:variables
}
